### ISSUE TITLE
Can't Launch HomeBridge

### ISSUE THREAD

**Issue by phybersplice** [beele/HomebridgeUnifiProtectMotion#1]
Hi,

I've tried to add one sensor for now, but can't get homebridge to launch after adding it to config.json.

Here's the startup log.
pi@raspberrypi:~ $ sudo homebridge restart
[2019-6-2 08:15:13] config.json (/root/.homebridge/config.json) not found.
[2019-6-2 08:15:14] Loaded plugin: homebridge-camera-ffmpeg
[2019-6-2 08:15:14] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[2019-6-2 08:15:14] ---
[2019-6-2 08:15:15] Loaded plugin: homebridge-camera-ffmpeg-omx
[2019-6-2 08:15:15] Registering platform 'homebridge-camera-ffmpeg-omx.Camera-ffmpeg-omx'
[2019-6-2 08:15:15] ---
[2019-6-2 08:15:15] Loaded plugin: homebridge-skybell
[2019-6-2 08:15:15] Registering platform 'homebridge-skybell.SkyBell'
[2019-6-2 08:15:15] ---
[2019-6-2 08:15:15] Plugin /usr/lib/node_modules/homebridge-unifi-protect-motion-sensors requires Node version of >=10.15.1 which does not satisfy the current Node version of v8.16.0. You may need to upgrade your installation of Node.
[2019-6-2 08:15:16] Loaded plugin: homebridge-unifi-protect-motion-sensors
[2019-6-2 08:15:16] Registering platform 'homebridge-unifi-protect-motion.Unifi-Protect-Motion'
[2019-6-2 08:15:16] ---
Load homebridge-camera-ffmpeg.Camera-ffmpeg
Load homebridge-camera-ffmpeg-omx.Camera-ffmpeg-omx
Load homebridge-unifi-protect-motion.Unifi-Protect-Motion
[2019-6-2 08:15:16] [homebridge-unifi-protect-motion.Unifi-Protect-Motion] Unifi-Protect-Motion Platform Init
[2019-6-2 08:15:16] TypeError: Cannot read property 'controller' of null
    at new UnifiProtectMotionPlatform (/usr/lib/node_modules/homebridge-unifi-protect-motion-sensors/src/index.js:44:19)
    at Server._loadDynamicPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:358:30)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:92:8)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
[2019-6-2 08:15:16] Got SIGTERM, shutting down Homebridge...

Here's my config.json which passed the JSON validators online.

`{
   "bridge":{
      "name":"Homebridge",
      "username":"11:22:33:44:55:66",
      "port":51826,
      "pin":"123-45-678"
   },
   "platforms":[
      {
         "platform":"SkyBell",
         "username":"yyyyy",
         "password":"xxxxx"
      },
{
    "platform": "Unifi-Protect-Motion",
    "name": "Bedroom",
    "room": "Master Bedroom",
    "controller": "https://192.168.1.10:7443",
    "username": "yyyy",
    "password": "xxxxx",
    "motionscore": "50",
    "motioninterval": "15",
    "delay": "15",
    "retries": "2"
},

      {
         "platform":"Camera-ffmpeg-omx",
         "cameras":[
            {
               "name":"Living Room",
               "videoConfig":{
                  "source":"-rtsp_transport http -re -i rtsp://192.168.1.10:7447/KphzXaU4q7Q9WLLW",
                  "vcodec":"h264_omx",
                  "audio":true,
                  "maxStreams":2,
                  "maxWidth":640,
                  "maxHeight":480,
                  "maxFPS":15,
                  "debug":true
               }
            },
            {
               "name":"Bedroom",
               "videoConfig":{
                  "source":"-rtsp_transport http -re -i rtsp://192.168.1.10:7447/YCy2EPoEk6SpQMzf",
                  "vcodec":"h264_omx",
                  "audio":true,
                  "maxStreams":2,
                  "maxWidth":640,
                  "maxHeight":480,
                  "maxFPS":15,
                  "debug":true
               }
            },
            {
               "name":"Driveway",
               "videoConfig":{
                  "source":"-rtsp_transport http -re -i rtsp://192.168.1.10:7447/CCXr2QmPGjMyP9AB",
                  "vcodec":"h264_omx",
                  "audio":true,
                  "maxStreams":2,
                  "maxWidth":640,
                  "maxHeight":480,
                  "maxFPS":15,
                  "debug":true
               }
            }
         ]
      }
   ]
}
`

**Comment by beele** [comment]
You should use no quotes for the numbers (motionscore/motioninterval/delay/retries), and the motionInterval should be in milliseconds, not seconds.
Other than that it looks ok to me.

My platform config looks like
```
{
            "platform": "Unifi-Protect-Motion",
            "name": "Unifi motion sensors",
            "room": "roomName",
            "controller": "https://ip-of-cloudkey-gen2-plus:7443",
            "motionscore": 50,
            "motioninterval": 10000,
            "username": "usernameGoesHere",
            "password": "passwordGoesHere",
            "delay": 500,
            "retries": 2
}
```

I'll adjust the readme to be more clear in the coming days.

**Comment by iFac3** [comment]
Hi! Thanks for this plugin! 

I have a question. Do I need make configs for all the rooms where I have UVC installed?

Rgds,
